<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Brand extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Brand_model');
    } 

    /*
     * Listing of brands
     */
    function index()
    {
        $this->Common_model->checklogin();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('brand/index?');
        $config['total_rows'] = $this->Brand_model->get_all_brands_count();
        $this->pagination->initialize($config);

        $data['brands'] = $this->Brand_model->get_all_brands($params);
        
        $data['_view'] = 'brand/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new brand
     */
    function add()
    {   
        $this->Common_model->checklogin();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'remark' => $this->input->post('remark'),
				'created' => date("Y-m-d"),
            );            
            $msg = $this->Brand_model->add_brand($params);   

            $this->load->library('upload');            
            $path =  $this->config->item('basepath');
            if( !empty($_FILES["logo"]["name"]))
            {
                $config['upload_path'] = $path.'upload/brand';
                $config['file_name'] = $msg.'_'.$_FILES["logo"]["name"];
                $config['overwrite']    = TRUE; 
                $config['allowed_types'] = 'gif|jpg|png|jpeg';
                $config['max_size'] = '5000';
                $this->upload->initialize($config);
                if (!$this->upload->do_upload("logo")){
                    $data['error'] =  $this->upload->display_errors();   
                }    
                else{                           
                    $data = array('upload_data' => $this->upload->data());
                    $imagename = $data['upload_data']['file_name'];                             
                }   
            }
            else
            {
                $imagename='';
            }
               
            $datainfo = array(
                'logo'=>$imagename,
            );
            $this->Brand_model->update_brand($msg,$datainfo);            
            redirect('brand/index');            
        }
        else
        {
            $data['_view'] = 'brand/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a brand
     */
    function edit($id)
    {   
        $this->Common_model->checklogin();
        // check if the brand exists before trying to edit it
        $data['brand'] = $this->Brand_model->get_brand($id);
        
        if(isset($data['brand']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
			$this->form_validation->set_rules('remark','Remark','required');
		
			if($this->form_validation->run())     
            {   
                $this->load->library('upload');
                $this->load->library('image_lib');
                $path =  $this->config->item('basepath');                
                if( !empty($_FILES["logo"]["name"])){
                    $config['upload_path'] = $path.'upload/brand';
                    $config['file_name'] = $data['brand']['id'].'_'.$_FILES["logo"]["name"];
                    $config['overwrite']    = TRUE; 
                    $config['allowed_types'] = 'gif|jpg|png|jpeg';
                    $config['max_size'] = '5000';
                    $this->upload->initialize($config);
                    if ( !$this->upload->do_upload("logo"))
                    {
                        $data['error'] =  $this->upload->display_errors();   
                    }    
                    else 
                    {
                        $filepath=$path.'upload/brand/'.$_REQUEST['image_copy'];
                        if (file_exists($filepath)) {
                            unlink($filepath); 
                        }
                        $mdata = array('upload_data' => $this->upload->data());
                        $imagename = $mdata['upload_data']['file_name'];                             
                    }                 
                }
                else
                {
                    $imagename=$_REQUEST['image_copy'];
                }

                $params = array(
                    'name' => $this->input->post('name'),
                    'remark' => $this->input->post('remark'),
                    'logo' => $imagename,
                );

                $this->Brand_model->update_brand($id,$params);            
                redirect('brand/index');
            }
            else
            {
                $data['_view'] = 'brand/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The brand you are trying to edit does not exist.');
    } 

    /*
     * Deleting brand
     */
    function remove($id)
    {
        $this->Common_model->checklogin();
        $brand = $this->Brand_model->get_brand($id);

        // check if the brand exists before trying to delete it
        if(isset($brand['id']))
        {
            $path =  $this->config->item('basepath');
            $filepath=$path.'upload/brand/'.$brand['logo'];
            if (file_exists($filepath)) {
                unlink($filepath); 
            }

            $this->Brand_model->delete_brand($id);
            redirect('brand/index');
        }
        else
            show_error('The brand you are trying to delete does not exist.');
    }
    
}
