<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Car_make extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Car_make_model');
    } 

    /*
     * Listing of car_make
     */
    function index()
    {
        $this->Common_model->checklogin();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('car_make/index?');
        $config['total_rows'] = $this->Car_make_model->get_all_car_make_count();
        $this->pagination->initialize($config);

        $data['car_make'] = $this->Car_make_model->get_all_car_make($params);
        
        $data['_view'] = 'car_make/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new car_make
     */
    function add()
    {   
        $this->Common_model->checklogin();
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'created' => date("Y-m-d"),
            );            
            $msg = $this->Car_make_model->add_car_make($params);   

            $this->load->library('upload');            
            $path =  $this->config->item('basepath');
           // print_r($_FILES);
            if( !empty($_FILES["logo"]["name"]))
            {
                $config['upload_path'] = $path.'upload/car_make';
                $config['file_name'] = $msg.'_'.$_FILES["logo"]["name"];
                $config['overwrite']    = TRUE; 
                $config['allowed_types'] = 'gif|jpg|png|jpeg';
                $config['max_size'] = '5000';
                $this->upload->initialize($config);
                if (!$this->upload->do_upload("logo")){
                    $data['error'] =  $this->upload->display_errors();   
                }    
                else{                           
                    $data = array('upload_data' => $this->upload->data());
                   // print_r($data);
                    $imagename = $data['upload_data']['file_name'];                             
                }   
            }
            else
            {
                $imagename='';
            }
               
            $datainfo = array(
                'logo'=>$imagename,
            );
            
            $this->Car_make_model->update_car_make($msg,$datainfo);            
            redirect('car_make/index');            
        }
        else
        {
            $data['_view'] = 'car_make/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a car_make
     */
    function edit($id)
    {   
        $this->Common_model->checklogin();
        // check if the car_make exists before trying to edit it
        $data['car_make'] = $this->Car_make_model->get_car_make($id);
        
        if(isset($data['car_make']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
		
			if($this->form_validation->run())     
            {   
                $this->load->library('upload');
                $this->load->library('image_lib');
                $path =  $this->config->item('basepath');                
                if( !empty($_FILES["logo"]["name"])){
                    $config['upload_path'] = $path.'upload/car_make';
                    $config['file_name'] = $data['car_make']['id'].'_'.$_FILES["logo"]["name"];
                    $config['overwrite']    = TRUE; 
                    $config['allowed_types'] = 'gif|jpg|png|jpeg';
                    $config['max_size'] = '5000';
                    $this->upload->initialize($config);
                    if ( !$this->upload->do_upload("logo"))
                    {
                        $data['error'] =  $this->upload->display_errors();   
                    }    
                    else 
                    {
                        $filepath=$path.'upload/car_make/'.$_REQUEST['image_copy'];
                        if (file_exists($filepath)) {
                            unlink($filepath); 
                        }
                        $mdata = array('upload_data' => $this->upload->data());
                        $imagename = $mdata['upload_data']['file_name'];                             
                    }                 
                }
                else
                {
                    $imagename=$_REQUEST['image_copy'];
                }

                $params = array(
                    'name' => $this->input->post('name'),
                    'logo' => $imagename,
                );

                $this->Car_make_model->update_car_make($id,$params);            
                redirect('car_make/index');
            }
            else
            {
                $data['_view'] = 'car_make/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The car_make you are trying to edit does not exist.');
    } 

    /*
     * Deleting car_make
     */
    function remove($id)
    {
        $this->Common_model->checklogin();
        $car_make = $this->Car_make_model->get_car_make($id);

        // check if the car_make exists before trying to delete it
        if(isset($car_make['id']))
        {
            $path =  $this->config->item('basepath');
            $filepath=$path.'upload/car_make/'.$car_make['logo'];
            if (file_exists($filepath)) {
                unlink($filepath); 
            }

            $this->Car_make_model->delete_car_make($id);
            redirect('car_make/index');
        }
        else
            show_error('The car_make you are trying to delete does not exist.');
    }
    
}
