<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carmodel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Carmodel_model');
        $this->load->model('Car_make_model');
    } 

    /*
     * Listing of carmodel
     */
    function index()
    {
        $this->Common_model->checklogin();
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('carmodel/index?');
        $config['total_rows'] = $this->Carmodel_model->get_all_carmodel_count();
        $this->pagination->initialize($config);

        $data['carmodel'] = $this->Carmodel_model->get_all_carmodel($params);
        
        $data['_view'] = 'carmodel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new carmodel
     */
    function add()
    {   
        $this->Common_model->checklogin();
        $this->load->library('form_validation');

        $this->form_validation->set_rules('car_make_id','Car make','required');
		$this->form_validation->set_rules('model_no','Model no.','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'car_make_id' => $this->input->post('car_make_id'),
                'remark' => $this->input->post('remark'),
				'model_no' => $this->input->post('model_no'),
				'created' => date("Y-m-d"),
            );            
            $msg = $this->Carmodel_model->add_carmodel($params);   
            redirect('carmodel/index');            
        }
        else
        {
            $this->load->model('Car_make_model');
            $data['all_car_make'] = $this->Car_make_model->get_all_car_make();

            $data['_view'] = 'carmodel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a carmodel
     */
    function edit($id)
    {   
        $this->Common_model->checklogin();
        // check if the carmodel exists before trying to edit it
        $data['carmodel'] = $this->Carmodel_model->get_carmodel($id);
        
        if(isset($data['carmodel']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('car_make_id','Car make','required');
            $this->form_validation->set_rules('model_no','Model no.','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
                    'car_make_id' => $this->input->post('car_make_id'),
                    'remark' => $this->input->post('remark'),
                    'model_no' => $this->input->post('model_no'),
                );

                $this->Carmodel_model->update_carmodel($id,$params);            
                redirect('carmodel/index');
            }
            else
            {
                $this->load->model('Car_make_model');
                $data['all_car_make'] = $this->Car_make_model->get_all_car_make();

                $data['_view'] = 'carmodel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The Car model you are trying to edit does not exist.');
    } 

    /*
     * Deleting carmodel
     */
    function remove($id)
    {
        $this->Common_model->checklogin();
        $carmodel = $this->Carmodel_model->get_carmodel($id);

        // check if the carmodel exists before trying to delete it
        if(isset($carmodel['id']))
        {
            $this->Carmodel_model->delete_carmodel($id);
            redirect('carmodel/index');
        }
        else
            show_error('The Car model you are trying to delete does not exist.');
    }
    
}
