<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Category_model');
    } 

    /*
     * Listing of categories
     */
    function index()
    {
        $this->Common_model->checklogin();
        $data['categories'] = $this->Category_model->get_all_categories();
        
        $data['_view'] = 'category/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new category
     */
    function add()
    {  
        $this->Common_model->checklogin(); 
        $this->load->library('form_validation');

		$this->form_validation->set_rules('cat_name','Category Name','required');
		
		if($this->form_validation->run())     
        {   

            $status = $this->input->post('status');
            if($status == NULL || $status == null){
                $status = 0;
            }

            $params = array(
				'status' => $status,
				'cat_parent' => $this->input->post('cat_parent'),
				'cat_name' => $this->input->post('cat_name'),
            );
            
            $category_id = $this->Category_model->add_category($params);
            redirect('category/index');
        }
        else
        {            
            $data['_view'] = 'category/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a category
     */
    function edit($id)
    {   
        $this->Common_model->checklogin();
        // check if the category exists before trying to edit it
        $data['category'] = $this->Category_model->get_category($id);
        
        if(isset($data['category']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('cat_name','Category Name','required');
		
			if($this->form_validation->run())     
            {   
                $status = $this->input->post('status');
                if($status == NULL || $status == null){
                    $status = 0;
                }
                $params = array(
					'status' => $status,
					'cat_parent' => $this->input->post('cat_parent'),
					'cat_name' => $this->input->post('cat_name'),
                );

                $this->Category_model->update_category($id,$params);            
                redirect('category/index');
            }
            else
            {
                $data['_view'] = 'category/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The category you are trying to edit does not exist.');
    } 

    /*
     * Deleting category
     */
    function remove($id)
    {
        $this->Common_model->checklogin();
        $category = $this->Category_model->get_category($id);

        // check if the category exists before trying to delete it
        if(isset($category['id']))
        {
            $this->Category_model->delete_category($id);
            redirect('category/index');
        }
        else
            show_error('The category you are trying to delete does not exist.');
    }
    
}
