<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Setting extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Setting_model');
        $this->load->model('State_model');
    } 


    /*
     * Editing a setting
     */
    function index()
    {   
        $this->Common_model->checklogin();

        $id = 1;
        // check if the setting exists before trying to edit it
        $data['setting'] = $this->Setting_model->get_setting(1);
        //echo '<pre>';
        //print_r($data);
        
		if(isset($_POST) && !empty($_POST))     
        {                   
            $params = array(				
                'state_id' => $this->input->post('state_id'),
                'name' => $this->input->post('name'),
                'address' => $this->input->post('address'),
                'GSTIN' => $this->input->post('GSTIN'),
                'website' => $this->input->post('website'),
                'terms' => $this->input->post('terms'),

				'notification_email' => $this->input->post('notification_email'),
            );
            //print_r($params); exit;

            $this->Setting_model->update_setting($id,$params);  
            $path =  $this->config->item('basepath');  
             $this->load->library('upload');  
             $config['overwrite']    = TRUE; 
                $config['allowed_types'] = 'gif|jpg|png|jpeg';
                $config['max_size'] = '5000';
             $config['upload_path'] = $path.'upload/settings';
            
            if( !empty($_FILES["logo"]["name"]))
            { 
                $config['file_name'] = rand(100,999).$_FILES["logo"]["name"];
                $this->upload->initialize($config);
                if (!$this->upload->do_upload("logo")){
                    $data['error'] =  $this->upload->display_errors();   
                    print_r($data);
                }    
                else{                           
                    $data = array('upload_data' => $this->upload->data());
                    $params['logo'] = base_url().'upload/settings/'.$data['upload_data']['file_name'];                             
                }   
            }
            if( !empty($_FILES["signature"]["name"]))
            { 
                $config['file_name'] = rand(100,999).$_FILES["signature"]["name"];
                $this->upload->initialize($config);
                if (!$this->upload->do_upload("signature")){
                    $data['error'] =  $this->upload->display_errors();   
                }    
                else{                           
                    $data = array('upload_data' => $this->upload->data());
                    $params['signature'] = base_url().'upload/settings/'.$data['upload_data']['file_name'];                             
                }   
            }
            
      // echo '<pre>'; print_r($data);

        $this->Setting_model->update_setting($id,$params);            
        redirect('setting/index');
        }
        else
        {
            $this->load->model('State_model');
            $data['all_state'] = $this->State_model->get_all_state();

            $data['_view'] = 'setting/index';
            $this->load->view('layouts/main',$data);
        }
        //show_error('The setting you are trying to edit does not exist.');
    }     
}
