<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Album_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get album by id
     */
    function get_album($id)
    {
        return $this->db->get_where('album',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all album
     */
    function get_all_album($status='all')
    {
        if($status=='close')
        {
           $this->db->where('status', 0);
        }
        else if($status=='open')
        {
            $this->db->where('status', 1);
        }else
        {
            
        }

        $this->db->order_by('id', 'desc');
        return $this->db->get('album')->result_array();
    }
        
    /*
     * function to add new album
     */
    function add_album($params)
    {
        $this->db->insert('album',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update album
     */
    function update_album($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('album',$params);
    }
    
    /*
     * function to delete album
     */
    function delete_album($id)
    {
        return $this->db->delete('album',array('id'=>$id));
    }
}
