<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Brand_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get brand by id
     */
    function get_brand($id)
    {
        return $this->db->get_where('brands',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all brands count
     */
    function get_all_brands_count()
    {
        $this->db->from('brands');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all brands
     */
    function get_all_brands($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('brands')->result_array();
    }
        
    /*
     * function to add new brand
     */
    function add_brand($params)
    {
        $this->db->insert('brands',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update brand
     */
    function update_brand($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('brands',$params);
    }
    
    /*
     * function to delete brand
     */
    function delete_brand($id)
    {
        return $this->db->delete('brands',array('id'=>$id));
    }
}
