<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Car_make_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get car_make by id
     */
    function get_car_make($id)
    {
        return $this->db->get_where('car_make',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all car_make count
     */
    function get_all_car_make_count()
    {
        $this->db->from('car_make');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all car_make
     */
    function get_all_car_make($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('car_make')->result_array();
    }
        
    /*
     * function to add new car_make
     */
    function add_car_make($params)
    {
        $this->db->insert('car_make',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update car_make
     */
    function update_car_make($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('car_make',$params);
    }
    
    /*
     * function to delete car_make
     */
    function delete_car_make($id)
    {
        return $this->db->delete('car_make',array('id'=>$id));
        
    }
}
