<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Carmodel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get carmodel by id
     */
    function get_carmodel($id)
    {
        return $this->db->get_where('carmodel',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all carmodel count
     */
    function get_all_carmodel_count()
    {
        $this->db->from('carmodel');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all carmodel
     */
    function get_all_carmodel($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('carmodel')->result_array();
    }
        
    /*
     * function to add new carmodel
     */
    function add_carmodel($params)
    {
        $this->db->insert('carmodel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update carmodel
     */
    function update_carmodel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('carmodel',$params);
    }
    
    /*
     * function to delete carmodel
     */
    function delete_carmodel($id)
    {
        return $this->db->delete('carmodel',array('id'=>$id));
    }
}
