<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notes by id
     */
    function get_notes($id)
    {
        return $this->db->get_where('notes',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all notes
     */
    function get_all_notes($status='all')
    {
        if($status=='close')
        {
           $this->db->where('status', 0);
        }
        else if($status=='open')
        {
            $this->db->where('status', 1);
        }else
        {
            
        }

        $this->db->order_by('reminder_date', 'asc');
        
        return $this->db->get('notes')->result_array();
    }
        
    /*
     * function to add new notes
     */
    function add_notes($params)
    {
        $this->db->insert('notes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notes
     */
    function update_notes($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('notes',$params);
    }
    
    /*
     * function to delete notes
     */
    function delete_notes($id)
    {
        return $this->db->delete('notes',array('id'=>$id));
    }
}
