<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Order_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get order_detail by id
     */
    function get_order_detail($id)
    {
        return $this->db->get_where('order_details',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all order_details count
     */
    function get_all_order_details_count()
    {
        $this->db->from('order_details');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all order_details
     */
    function get_all_order_details($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('order_details')->result_array();
    }
        
    /*
     * function to add new order_detail
     */
    function add_order_detail($params)
    {
        $this->db->insert('order_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update order_detail
     */
    function update_order_detail($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('order_details',$params);
    }
    
    /*
     * function to delete order_detail
     */
    function delete_order_detail($id)
    {
        return $this->db->delete('order_details',array('id'=>$id));
    }
}
