<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Variations_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get variations by id
     */
    function get_variations($id)
    {
        return $this->db->get_where('variations',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all variations
     */
    function get_all_variations()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('variations')->result_array();
    }
        
    /*
     * function to add new variations
     */
    function add_variations($params)
    {
        $this->db->insert('variations',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update variations
     */
    function update_variations($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('variations',$params);
    }
    
    /*
     * function to delete variations
     */
    function delete_variations($id)
    {
        return $this->db->delete('variations',array('id'=>$id));
    }
}
